// packages/solid-uploads-list/src/resources/UploadsList.ts
import { createResource, InitializedResourceReturn, ResourceOptions, ResourceReturn, ResourceSource } from 'solid-js'
import type { Space } from '@w3ui/keyring-core'
import { list, ServiceConfig, UploadListResult } from '@w3ui/uploads-list-core'
import type { Capability, DID, Principal, Proof, Signer } from '@ucanto/interface'
import { list as uploadList } from '@web3-storage/access/capabilities/upload'

interface UploadsListSource extends ServiceConfig {
  space: Space,
  agent: Signer,
  getProofs: (caps: Capability[]) => Promise<Proof[]>
}

/**
 * Create a solid resource configured to fetch data from the service. Please
 * see the docs for [`createResource`](https://www.solidjs.com/docs/latest/api#createresource)
 * for parameter and return type descriptions.
 */
export function createUploadsListResource (source: ResourceSource<UploadsListSource>, options?: ResourceOptions<UploadListResult[], UploadsListSource>): ResourceReturn<UploadListResult[]> | InitializedResourceReturn<UploadListResult[]> {
  // TODO: WIRE IN CURSOR AND SIZE
  return createResource<UploadListResult[], UploadsListSource>(
    source,
    async ({ space, agent, servicePrincipal, connection, getProofs }) => {
      const conf = {
        issuer: agent,
        with: space.did(),
        audience: servicePrincipal,
        proofs: await getProofs([{ can: uploadList.can, with: space.did() }])
      }
      const page = await list(conf, { connection })
      return page.results ?? []
    },
    options
  )
}

// packages/react-uploads-list/src/providers/UploadsList.tsx
import React, { useContext, createContext, useState, ReactNode } from 'react'
import { UploadListResult, UploadsListContextState, UploadsListContextActions, ServiceConfig, list } from '@w3ui/uploads-list-core'
import { useKeyring } from '@w3ui/react-keyring'
import { list as uploadList } from '@web3-storage/access/capabilities/upload'

export type UploadsListContextValue = [
  state: UploadsListContextState,
  actions: UploadsListContextActions
]

const UploadsListContext = createContext<UploadsListContextValue>([
  {
    loading: false
  },
  {
    next: async () => {},
    reload: async () => {}
  }
])

export interface UploadsListProviderProps extends ServiceConfig {
  children?: ReactNode
  /**
   * Maximum number of items to return per page.
   */
  size?: number
}

/**
 * Provider for a list of items uploaded to the current space.
 */
export function UploadsListProvider ({ size, servicePrincipal, connection, children }: UploadsListProviderProps): ReactNode {
  const [{ space, agent }, { getProofs }] = useKeyring()
  const [cursor, setCursor] = useState<string>()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<Error>()
  const [data, setData] = useState<UploadListResult[]>()
  const [controller, setController] = useState(new AbortController())

  const loadPage = async (cursor?: string): Promise<void> => {
    if (space == null) return
    if (agent == null) return

    controller.abort()
    const newController = new AbortController()
    setController(newController)
    setLoading(true)

    try {
      const conf = {
        issuer: agent,
        with: space.did(),
        audience: servicePrincipal,
        proofs: await getProofs([{ can: uploadList.can, with: space.did() }])
      }
      const page = await list(conf, {
        cursor,
        size,
        signal: newController.signal,
        connection
      })
      setCursor(page.cursor)
      setData(page.results)
    } catch (err: any) {
      if (err.name !== 'AbortError') {
        console.error(err)
        // @ts-expect-error ts not know about cause
        setError(new Error('failed to fetch uploads list', { cause: err }))
      }
    } finally {
      setLoading(false)
    }
  }

  const state = { data, loading, error }
  const actions = {
    next: async (): Promise<void> => { await loadPage(cursor) },
    reload: loadPage
  }

  return (
    <UploadsListContext.Provider value={[state, actions]}>
      {children}
    </UploadsListContext.Provider>
  )
}

/**
 * Use the scoped uploads list context state from a parent `UploadsListProvider`.
 */
export function useUploadsList (): UploadsListContextValue {
  return useContext(UploadsListContext)
}
