// examples/solid/file-upload/src/components/Loader.jsx
import { For, Show } from "solid-js"

function StatusLoader ({ progressStatus }) {
  const { total, loaded, lengthComputable } = progressStatus
  return (
    <Show
      when={lengthComputable}
      fallback={<div className='spinner mr3 flex-none' />}>
      <div className='relative w2 h5 ba b--white flex flex-column justify-end'>
        <div className='bg-white w100' style={{ height: `${Math.floor((loaded / total) * 100)}%` }}>
        </div>
      </div>
    </Show>
  )
}

export default function Loader ({ progress, className = '' }) {
  return (
    <div className={`${className} flex flex-row`}>
      <For each={Object.values(progress.uploadProgress)}>
        {(status) => <StatusLoader progressStatus={status} key={status.url} />}
      </For>
    </div>
  )
}

// examples/react/components/src/Loader.tsx
import React from 'react'
import { ArrowPathIcon } from '@heroicons/react/20/solid'
import { ProgressStatus, UploadProgress } from '@w3ui/react'

function StatusLoader ({ progressStatus }: { progressStatus: ProgressStatus }) {
  const { total, loaded, lengthComputable } = progressStatus
  if (lengthComputable) {
    const percentComplete = Math.floor((loaded / total) * 100)
    return (
      <div className='relative w2 h5 ba b--white flex flex-column justify-end'>
        <div className='bg-white w100' style={{ height: `${percentComplete}%` }}>
        </div>
      </div>
    )
  } else {
    return <ArrowPathIcon className='animate-spin h-4 w-4' />
  }
}

interface LoaderProps {
  uploadProgress: UploadProgress
  className?: string
}

export function UploadLoader ({ uploadProgress, className = '' }: LoaderProps) {
  return (
    <div className={`${className} flex flex-row`}>
      {Object.values(uploadProgress).map(
        status => <StatusLoader progressStatus={status} key={status.url} />
      )}
    </div>
  )
}

export function Loader () {
  return <ArrowPathIcon className="animate-spin h-12 w-12 mx-auto mt-12" />
}
