// examples/vue/uploads-list/src/App.vue
<script>
import { KeyringProvider } from '@w3ui/vue-keyring'
import { UploadsListProvider } from '@w3ui/vue-uploads-list'
import Authenticator from './components/Authenticator.vue'
import ContentPage from './ContentPage.vue'

export default {
  components: { KeyringProvider, UploadsListProvider, Authenticator, ContentPage }
}
</script>

<template>
  <KeyringProvider>
    <UploadsListProvider>
      <div className="vh-100 flex flex-column justify-center items-center sans-serif light-silver">
        <header>
          <img src="./assets/logo.png" width="250" alt="logo" />
        </header>
        <Authenticator>
          <ContentPage />
        </Authenticator>
      </div>
    </UploadsListProvider>
  </KeyringProvider>
</template>

// examples/react/uploads-list/src/App.js
import React from 'react'
import { KeyringProvider } from '@w3ui/react-keyring'
import { UploadsListProvider } from '@w3ui/react-uploads-list'
import ContentPage from './ContentPage'
import logo from './logo.png'

function App () {
  return (
    <KeyringProvider>
      <UploadsListProvider>
        <div className='vh-100 flex flex-column justify-center items-center sans-serif light-silver'>
          <header>
            <img src={logo} width='250' alt='logo' />
          </header>
          <ContentPage />
        </div>
      </UploadsListProvider>
    </KeyringProvider>
  )
}

export default App
